# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

# Optional: Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

# Optional: Install a C compiler, cmake and git into the container.
# You will often need this when you (or any of your dependencies) depends on C code.
# before_script:
#   - apt-get update -yqq
#   - apt-get install -yqq --no-install-recommends build-essential

stages:
  - test
  - docs
  - build-debug
  - build-release

# Use cargo to test the project
test:
  stage: test
  script:
    - "echo \"Package: *\nPin: release a=unstable\nPin-Priority: 490\n\" | tee -a /etc/apt/preferences"
    - "echo \"deb http://deb.debian.org/debian unstable main contrib non-free\ndeb-src http://deb.debian.org/debian unstable main contrib non-free\n\" | tee -a /etc/apt/sources.list"
    - apt-get update && apt-get install -t unstable -y kcov
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
    - cargo build --workspace --verbose   # Needed for kcov
    - kcov target/cov target/debug/signal-gen-cjds66 || true
    - "COVERAGE=$(grep -Po 'percent_covered\":\\s+\\\"\\d+.\\d+\\\"' target/cov/signal-gen-cjds66.*/coverage.json | grep -Po '\\d+.\\d+' | tail -n 1)"
    - echo "Coverage:" $COVERAGE

# Use cargo to build the docs
docs:
  stage: docs
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo doc --workspace --verbose
  artifacts:
    expire_in: never
    paths:
      - target/doc

# Use cargo to build the debug project
build-debug:
  stage: build-debug
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo build --verbose
  artifacts:
    expire_in: never
    paths:
      - target/debug/signal-gen-cjds66

# Use cargo to build the release project
build-release:
  stage: build-release
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo build --release --verbose
  artifacts:
    expire_in: never
    paths:
      - target/release/signal-gen-cjds66
